CREATE SEQUENCE board_seq START WITH 1 INCREMENT BY 1 CYCLE NOCACHE;

CREATE TABLE board (
	id NUMBER(5) PRIMARY KEY,
	title VARCHAR(200),
	writer VARCHAR(20),
	content VARCHAR(2000),
	regdate	DATE DEFAULT SYSDATE,
	count NUMBER(5) DEFAULT 0
);